version: "3.8"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: site_2
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app2.rule=Host(`app2.localhost`)"
      - "traefik.http.services.app2.loadbalancer.server.port=80"
    networks:
      - app-network
      - traefik-network
    env_file:
      - ".env"
networks:
  app-network:
    external: true
  traefik-network:
    external: true
